export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAILED = "CREATE_TEACHER_FAILED";

export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILED = "CREATE_STUDENT_FAILED";

export const CREATE_CATHEDRA_SUCCESS = "CREATE_CATHEDRA_SUCCESS";
export const CREATE_CATHEDRA_FAILED = "CREATE_CATHEDRA_FAILED";

export const CREATE_DIRECTION_SUCCESS = "CREATE_DIRECTION_SUCCESS";
export const CREATE_DIRECTION_FAILED = "CREATE_DIRECTION_FAILED";

export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
